# config.py
# This file serves as the central configuration dashboard for the research app.
# All experimental parameters, prompts, models, and users are defined here.

# ==============================================================================
# --- 1. PRE-REGISTERED EXPERIMENTAL DESIGN (Do Not Modify) ---
# ==============================================================================
#
# CANONICAL STUDY DESIGN (Finalized 2026-03-28):
# - 1,620 runs generated via stratified randomizer
# - Seed: 42 (locked for reproducibility)
# - Mode: stratified_7day_balanced
# - Generation command: python scripts/test_randomizer_stratified.py --seed 42
#
# Balance properties:
# - 540 runs per engine (exact, ±0)
# - 540 runs per time slot (exact, ±0)
# - 179-181 runs per engine×time slot (stratified remainder distribution)
#
# ⚠️  CRITICAL WARNING: Constants vs Run Count
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# The constants below (PRODUCTS, MATERIALS, etc.) DO NOT multiply to 1,620.
# They define the INPUT SPACE for the stratified randomizer.
#
# ❌ WRONG: 3 × 3 × 3 × 3 × 3 × 3 = 729 runs (simple Cartesian product)
# ✅ RIGHT: 1,620 runs from stratified 7-day randomization
#
# The 1,620 runs come from:
#   - 7-day temporal structure (Monday-Sunday)
#   - 231-232 runs per day (stratified assignment)
#   - Product×material grouping within each day
#   - Post-hoc engine and time slot balancing
#
# DO NOT compute: PRODUCTS × MATERIALS × TEMPS × ... = run count
# DO compute: len(pd.read_csv('results/experiments.csv'))
#
# Modifying these constants will NOT change the experiment.
# The matrix is pre-generated and locked (results/experiments.csv).
# Regenerating the matrix invalidates pre-registration.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRODUCTS = (
    "smartphone_mid",
    "cryptocurrency_corecoin",
    "supplement_melatonin",
)

MATERIALS = (
    "faq.j2",
    "digital_ad.j2",
    "blog_post_promo.j2",
)

TIMES = (
    "morning",     # 7am-12pm (stratified assignment, not Cartesian)
    "afternoon",   # 12pm-5pm (stratified assignment, not Cartesian)
    "evening",     # 5pm-10pm (stratified assignment, not Cartesian)
)

TEMPS = (
    0.2,  # low - more deterministic
    0.6,  # medium - balanced
    1.0,  # high - more creative
)

REPS = (1, 2, 3)  # Used internally by stratified randomizer

ENGINES = (
    "openai",
    "google",
    "mistral",
)

# Verification: Simple Cartesian product would be 3×3×3×3×3×3 = 729 runs.
# The canonical design is 1,620 runs (stratified, not Cartesian).
# DO NOT use these constants for row counting - use len(experiments.csv) instead.

# ==============================================================================
# --- RUNTIME CONFIGURATION (Can Be Modified) ---
# ==============================================================================

# Engine-to-model mapping (can be updated if models change or new versions released)
ENGINE_MODELS = {
    "openai": "gpt-4o",  # Upgraded from gpt-4o-mini to full gpt-4o
    "google": "models/gemini-flash-latest",  # Latest stable Gemini Flash
    "mistral": "mistral-large-2407",  # Large model (July 2024) - better quality for research
    "anthropic": "claude-3-opus-20240229",  # Claude 3 Opus (your API key tier)
}

REGION = "US"

# Randomization / scheduling controls
# NOTE: The canonical 1,620-run matrix is generated by the stratified randomizer:
#   python scripts/test_randomizer_stratified.py --seed 42
# This creates results/experiments.csv with pre-registered randomization protocol.
# The orchestrator then executes runs according to that locked schedule.
MATRIX_RANDOMIZATION_SEED = 42
ENABLE_TRUE_TEMPORAL_SCHEDULING = False
TEMPORAL_WINDOW_HOURS = 72.0
EXPERIMENT_START_ISO = ""  # Example: "2026-04-03T00:00:00+00:00"

# --- 2. METADATA AND REPRODUCIBILITY SETTINGS ---

# Default values for metadata tracking (statistical validity)
DEFAULT_MAX_TOKENS = 2000           # Max completion tokens
DEFAULT_SEED = 12345                # Fixed seed for reproducibility
DEFAULT_TOP_P = None                # Use API default (1.0), set to float to override
DEFAULT_FREQUENCY_PENALTY = None    # Use API default (0.0), set to float to override
DEFAULT_PRESENCE_PENALTY = None     # Use API default (0.0), set to float to override

# Session tracking
DEFAULT_SESSION_ID = "main_experiment"  # Can be overridden via CLI --session-id

# --- 3. USER ACCOUNTS ---
# Single user setup for current research
USER_ACCOUNTS = [
    "researcher_primary",  # Single user for now
]

# Default account for experiments
DEFAULT_ACCOUNT_ID = USER_ACCOUNTS[0]

# --- 3. LEGACY CONFIGURATIONS (ARCHIVED) ---
# NOTE: MODEL_CONFIGURATIONS, STANDARDIZED_PROMPTS, and get_model_config()
# were moved to archive/legacy_config.py on 2025-10-06.
#
# These were used by the deprecated interactive CLI (archive/main.py).
# The batch system uses ENGINE_MODELS (above) and Jinja2 templates (prompts/*.j2) instead.
#
# If you need these for reference, see: archive/legacy_config.py
